export { default as About } from "./About";
export { default as ContactPage } from "./Contact";
export { default as FAQ } from "./FAQ";
export { default as Favourites } from "./Favourites";
export { default as Home } from "./Home";
export { default as NotFound } from "./NotFound";
export { default as Search } from "./Search";
export { default as Shopping } from "./Shopping";
export { default as StoreLocator } from "./StoreLocator";
